# Analysis Params
START: FASTQ # FASTQ, BAM, COUNT, RNK
PAIR_END: False  # True/False
ALIGNER: STAR
ADAPTORS: meta/adapters/merged.fa
GENOME: resources/genome/mm10.chr19.fa
#/home/rui.li-umw/genomes/mm10/mm10.ucsc.fa
#/home/rui.li-umw/genomes/hg38/hg38.primary.fa
INDEX: resources/genome/mm10.chr19.fa.star_idx
#/home/rui.li-umw/genomes/mm10/star_idx
#/home/rui.li-umw/genomes/hg38/star_idx
GTF: resources/genome/gencode.vM25.primary_assembly.annotation.ch19.gtf
#/home/rui.li-umw/genomes/mm10/gencode.vM25.primary_assembly.annotation.gtf
#/home/rui.li-umw/genomes/hg38/gencode.v34.primary_assembly.annotation.gtf
ANNO_TAB:  https://raw.githubusercontent.com/radio1988/OneStopRNAseq/master/snakemake/workflow/resources/anno_tables/mm10.gencode.vm25.te_included.anno.txt
#https://raw.githubusercontent.com/radio1988/OneStopRNAseq/master/snakemake/envs/anno_tables/hg38.gencode.v34.te_included.anno.txt
STRAND: [0, 1, 2]  # can input [0, 1, 2] to get all possible results, then workflow auto inferrs the correct one 
# [2] if you know it's reverse, [1] if you know it's forward, [0] if you know it's un-stranded
# todo refine auto select
MODE: strict # liberal: Multi-Mapping, No fragment size reqirement; strict: opposite
INTRON: False  # will also perform gene level featureCount as well as exon level, and max(gene-count, exon-count) will be taken as gene-count

# DESeq2
DESEQ2_ANALYSIS: True
MAX_FDR: 0.05
MIN_LFC: 0.585 
META: meta/meta.xlsx
CONTRAST_DE: meta/contrast.de.xlsx
cooksCutoff: 'FALSE'
independentFilter: 'FALSE'
blackSamples: 'sampleXXXXX,sampleYYY' # list of sample names to remove as outlier, e.g. KO_D0_1_S2, excluded in DESeq2 analysis only, optional


# GSEA
GSEA_ANALYSIS: True
GSEA_NPLOTS: 100  
GSEA_PLOT_SVG: False  
GSEA_DB_PATH: workflow/resources/gsea_db/mus_musculus/gsea_db/


# Only if start from COUNT
COUNT_FILE: meta/COUNT.xlsx  # must have same format as feature_count output c1-c7 meta, c7- count
# both txt and xlsx supported, meta/COUNT.xlsx will be converted to meta/COUNT.xlsx.txt
# meta/COUNT.txt will be read as is

# Only if start from RNK
RNKS:
  - name1.rnk.txt  # under ./meta/name1.rnk.txt
  - name2.rnk.txt  # under ./meta/name2.rnk.txt

# Optinoal Analysis

# Alternative Splicing analysis (rMATS)
DEXSEQ_ANALYSIS: True
RMATS_ANALYSIS: True
CONTRAST_AS: meta/contrast.as.xlsx
RMATS_STRANDNESS:
  {0 : fr-unstranded,
  1 : fr-firststrand, 
  2 : fr-secondstrand}

# DEXSeq analysis
MIN_GENE_COUNT: 100  # genes with less reads per sample will be removed from DEXSeq analysis

# TE analysis (SalmonTE)
TE_ANALYSIS: True # True, include TE analysis in DESeq2 results (only if FASTQ provided); False, skip
TE_REFERENCE: mm # mm, hs, dm, dr
# hs : Homo Sapiens
# mm : Mus musculus
# dm : Drosophila melanogaster
# dr : Danio rerio

# For ASE
ASE_ANALYSIS: False
VCF: example_data/genome/mm10_chr19/BALB_cJ.mgp.v5.indels.dbSNP142.normed.chr.vcf

ASSEMBLY_ANALYSIS: True
# todo: DE analysis with new ASSEMBLY GTF
