# Data parameters
SAMPLES:
    - KO_D0_1_S2
    - KO_D0_2_S8
    - KO_D2_1_S4
    - KO_D2_2_S10
    - KO_D8_1_S6
    - KO_D8_2_S12
    - WT_D0_1_S1
    - WT_D0_2_S7
    - WT_D2_1_S3
    - WT_D2_2_S9
    - WT_D8_1_S5
    - WT_D8_2_S11

START: FASTQ # FASTQ, BAM, COUNT, RNK # starting point of workflow

PAIR_END: True  # True/False # Only change if start from FASTQ or BAM

GENOME: example_data/genome/mm10_chr19/mm10.chr19.fa #'fa' and 'fa.gz' both supported

INDEX: example_data/genome/mm10_chr19/star_idx # STAR index # will be created if not exist

GTF: example_data/genome/mm10_chr19/gencode.vM25.primary_assembly.annotation.ch19.gtf #'gtf' or 'gtf.gz' both supported

ANNO_TAB: https://raw.githubusercontent.com/radio1988/OneStopRNAseq/master/snakemake/envs/anno_tables/mm10.gencode.vm25.te_included.anno.txt
#view all options from: https://github.com/radio1988/OneStopRNAseq/tree/master/snakemake/envs/anno_tables


# Analysis parameters
## featureCounts
STRAND: [0, 1, 2]  # [0, 1, 2]  for autodetection
# [2] if you know it's reverse, [1] if you know it's forward, [0] if you know it's un-stranded
MODE: strict # liberal: Multi-Mapping reads counted, No fragment size filter; strict: opposite
INTRON: False  # True/False # max(gene-count, exon-count) will be taken as gene-count, to include intron reads, default is False

## DESeq2
DESEQ2_ANALYSIS: True
MAX_FDR: 0.05 # cut-off for significant DEG
MIN_LFC: 0.585 # cut-off for significant DEG
META: meta/meta.xlsx # excel table to store meta-data for samples
CONTRAST_DE: meta/contrast.de.xlsx # excel table to store comparison/contrast needed
cooksCutoff: 'TRUE'  # 'TRUE'/'FALSE', single quote needed
independentFilter: 'FALSE'  # 'TRUE'/'FALSE', single quote needed

## GSEA
GSEA_ANALYSIS: True
GSEA_NPLOTS: 100 # num of top gene set to be plotted 
GSEA_PLOT_SVG: True  
GSEA_DBS: # MSigDB or custom gene set gmt files to choose from 
#  - c1.all.v7.1.symbols.gmt
#  - c2.cgp.v7.1.symbols.gmt
#  - c2.cp.v7.1.symbols.gmt
#  - c3.all.v7.1.symbols.gmt
#  - c4.all.v7.1.symbols.gmt
#  - c5.bp.v7.1.symbols.gmt
#  - c5.cc.v7.1.symbols.gmt
#  - c5.mf.v7.1.symbols.gmt
#  - c6.all.v7.1.symbols.gmt
#  - c7.all.v7.1.symbols.gmt
  - h.all.v7.1.symbols.gmt 

## Alternative Splicing analysis (rMATS)
DEXSEQ_ANALYSIS: False # example dataset to small to perform DEXSeq analysis
RMATS_ANALYSIS: True
CONTRAST_AS: meta/contrast.as.xlsx

# DEXSeq analysis
MIN_GENE_COUNT: 100  # genes with less reads per sample will be removed from DEXSeq analysis

# TE analysis (SalmonTE)
TE_ANALYSIS: False # True, include TE analysis in DESeq2 results (only if FASTQ provided); False, skip
TE_REFERENCE: mm # mm, hs, dm, dr
# hs : Homo Sapiens
# mm : Mus musculus
# dm : Drosophila melanogaster
# dr : Danio rerio

# For ASE
ASE_ANALYSIS: False  # True/False
VCF: example_data/genome/mm10_chr19/BALB_cJ.mgp.v5.indels.dbSNP142.normed.chr.vcf

# Hisat, stringtie assembly analysis
ASSEMBLY_ANALYSIS: True  # True/False

# Only change if start from COUNT
COUNT_FILE: placeholder

# Only change if start from RNK
RNKS:
  - placeholder
